### ISSUE TITLE
Adatbázis elkészítése

### ISSUE THREAD

**Issue by MartonBenjamin** [MartonBenjamin/prolab#8]
- [x] Userek
- [x] Megrendelések
- [x] Alkalmazottak nyilvántartása
- [x] Garázskapuk és a hozzá kapcsolódó adatok táblái
- [ ] Reklamációs adatok tábla
- [x] Árajánlatok tábla
- [x] Elvégzendő munkák/szervizelések tábla

**Comment by nerofor** [comment]
Azt írta a feladatleírás, hogy a telepítés a szerelő csapattal történik. Akkor legyenek az egyes dolgozók csapatokba/csoportokba szervezhetők? Mert akkor mindenképp kell egy segédtábla amiben tárolva vannak ezek az információk, és akkor nem csak a munkások lehetnek külön egységekbe szervezve hanem a szervezet minden tagja. Csupán a kérdés az, hogy szükség van-e rá?
